.pragma library

function generate(colors, opacity, mode, context) {
    const base = colors.base00 || "#000000";
    const surface = colors.base01 || base;
    const muted = colors.base04 || "#6a6a7a";
    const text = colors.base05 || "#ffffff";
    const error = colors.base08 || "#ff0000";
    const warning = colors.base09 || "#ffff00";
    const accent = colors.base0A || "#ffff00";
    const success = colors.base0B || "#00ff00";
    const cyan = colors.base0C || "#00ffff";
    const primary = colors[colors.primaryIdx] || colors.base0D;
    const secondary = colors[colors.secondaryIdx] || colors.base0E;

    let content = `# Generated by Yaks
foreground = ${text}
background = ${surface}
cursor-color = ${primary}
selection-background = ${surface}
selection-foreground = ${text}

palette = 0=${surface}
palette = 1=${error}
palette = 2=${success}
palette = 3=${warning}
palette = 4=${primary}
palette = 5=${secondary}
palette = 6=${cyan}
palette = 7=${muted}
palette = 8=${muted}
palette = 9=${error}
palette = 10=${success}
palette = 11=${warning}
palette = 12=${primary}
palette = 13=${secondary}
palette = 14=${cyan}
palette = 15=${text}
`;

    if (opacity !== undefined && opacity !== null && opacity !== "") {
        content += `\nbackground-opacity = ${opacity}\n`;
    }

    const reloadCommand = `
        (pkill -USR2 ghostty || true) &
    `;

    return {
        destination: "~/.cache/quickshell/themes/ghostty",
        content: content,
        reloadCommand: reloadCommand
    };
}
