.pragma library

function generate(colors, opacity, mode, context) {
    const bg = colors.base00 || "#000000";
    const surface = colors.base01 || bg;
    const text = colors.base05 || "#ffffff";
    const primary = colors[colors.primaryIdx] || colors.base0D;
    const accent = colors.base0A || primary;
    const error = colors.base08 || "#ff5555";
    const warning = colors.base09 || "#ffcc00";
    const success = colors.base0B || "#55ff55";

    opacity = opacity !== undefined && opacity !== null ? opacity : 1.0;
    
    function hexToRgba(hex, alpha) {
        hex = hex.replace("#", "");
        if (hex.length !== 6) return hex;
        const r = parseInt(hex.substring(0, 2), 16);
        const g = parseInt(hex.substring(2, 4), 16);
        const b = parseInt(hex.substring(4, 6), 16);
        return `rgba(${r}, ${g}, ${b}, ${alpha})`;
    }

    const bgRgba = hexToRgba(bg, opacity);
    const surfaceRgba = hexToRgba(surface, opacity);

    const commonTop = `/* Generated by Quickshell Tokens Sync */
@define-color accent_color ${accent};
@define-color accent_bg_color ${accent};
@define-color accent_fg_color ${bg};

@define-color error_color ${error};
@define-color error_bg_color ${error};
@define-color error_fg_color ${bg};

@define-color warning_color ${warning};
@define-color warning_bg_color ${warning};
@define-color warning_fg_color ${bg};

@define-color success_color ${success};
@define-color success_bg_color ${success};
@define-color success_fg_color ${bg};

@define-color destructive_bg_color ${error};
@define-color destructive_fg_color ${bg};

@define-color window_bg_color ${bgRgba};
@define-color window_fg_color ${text};
@define-color view_bg_color ${surfaceRgba};
@define-color view_fg_color ${text};
@define-color headerbar_bg_color transparent;
@define-color headerbar_fg_color ${text};
@define-color card_bg_color ${surfaceRgba};
@define-color dialog_bg_color ${surfaceRgba};
@define-color popover_bg_color ${surfaceRgba};
@define-color sidebar_bg_color transparent;
@define-color sidebar_fg_color ${text};
@define-color sidebar_backdrop_color transparent;
@define-color secondary_sidebar_bg_color transparent;
@define-color secondary_sidebar_backdrop_color transparent;
@define-color border_color ${surfaceRgba};
@define-color separator_color ${surfaceRgba};
@define-color outline_color ${surfaceRgba};
@define-color window_outline_color ${surfaceRgba};

/* Noctalia Specific Coherence Tokens */
@define-color overview_bg_color ${surfaceRgba};
@define-color overview_fg_color ${text};
@define-color sidebar_border_color transparent;
`;

    const gtk3Mid = `
/* Backdrop (Unfocused) states - GTK3 & Standard */
@define-color theme_unfocused_fg_color ${text};
@define-color theme_unfocused_text_color ${text};
@define-color theme_unfocused_bg_color ${bgRgba};
@define-color theme_unfocused_base_color ${bgRgba};
@define-color theme_unfocused_selected_bg_color ${accent};
@define-color theme_unfocused_selected_fg_color ${bg};

@define-color window_bg_color_backdrop ${bgRgba};
@define-color window_fg_color_backdrop ${text};
@define-color sidebar_bg_color_backdrop transparent;
@define-color sidebar_fg_color_backdrop ${text};
@define-color headerbar_bg_color_backdrop transparent;
@define-color headerbar_fg_color_backdrop ${text};
`;

    const gtk4Mid = `
/* Backdrop (Unfocused) states */
@define-color window_bg_color_backdrop ${bgRgba};
@define-color window_fg_color_backdrop ${text};
@define-color sidebar_bg_color_backdrop transparent;
@define-color sidebar_fg_color_backdrop ${text};
@define-color headerbar_bg_color_backdrop transparent;
@define-color headerbar_fg_color_backdrop ${text};

/* GTK4 :root Variables for modern Libadwaita support */
:root {
    --accent-color: ${accent};
    --accent-bg-color: ${accent};
    --accent-fg-color: ${bg};

    --window-bg-color: ${bgRgba};
    --window-fg-color: ${text};

    --view-bg-color: ${surfaceRgba};
    --view-fg-color: ${text};

    --headerbar-bg-color: transparent;
    --headerbar-fg-color: ${text};
    --headerbar-backdrop-color: ${bgRgba};

    --sidebar-bg-color: transparent;
    --sidebar-fg-color: ${text};
    --sidebar-backdrop-color: transparent;

    --popover-bg-color: ${surfaceRgba};
    --popover-fg-color: ${text};

    --card-bg-color: ${surfaceRgba};
    --card-fg-color: ${text};

    --dialog-bg-color: ${surfaceRgba};
    --dialog-fg-color: ${text};

    --error-color: ${error};
    --error-bg-color: ${error};
    --error-fg-color: ${bg};

    --warning-color: ${warning};
    --warning-bg-color: ${warning};
    --warning-fg-color: ${bg};

    --success-color: ${success};
    --success-bg-color: ${success};
    --success-fg-color: ${bg};

    --destructive-bg-color: ${error};
    --destructive-fg-color: ${bg};
}
`;

    const commonBottom = `
/* --- Aggressive Overrides (Focus & Backdrop Consistency) --- */

/* Only the top-level window carries the background color */
window, 
window:backdrop {
    background-color: ${bgRgba} !important;
    color: ${text} !important;
    opacity: 1 !important;
}

/* All other layout containers must be transparent to prevent stacking/layering */
.background,
.background:backdrop,
headerbar, 
headerbar:backdrop,
.titlebar,
.titlebar:backdrop,
.navigation-sidebar, 
.navigation-sidebar:backdrop,
.sidebar, 
.sidebar:backdrop,
adwviewstack, 
adwviewstack:backdrop,
adwleaflet,
adwleaflet:backdrop,
adwsplitview,
adwsplitview:backdrop,
adwnavigationview,
adwnavigationview:backdrop,
deck,
overlay {
    background-color: transparent !important;
    background-image: none !important;
    border: none !important;
    box-shadow: none !important;
    color: ${text} !important;
    opacity: 1 !important;
    transition: none !important;
}

/* Ensure separators and borders between panels respect theme opacity */
separator, 
.separator, 
gutter,
.gutter,
.view-sidebar-separator {
    background-color: ${surfaceRgba} !important;
    background-image: none !important;
    border: none !important;
    box-shadow: none !important;
    min-width: 1px;
    min-height: 1px;
    opacity: 1 !important;
}

/* Fix for Nautilus specifically - Content Area */
.view, .view:backdrop,
list, list:backdrop,
gridview, gridview:backdrop,
.nautilus-window notebook stack {
    background-color: ${surfaceRgba} !important;
    color: ${text} !important;
    opacity: 1 !important;
}

/* Ensure active items in sidebar still look distinct */
.navigation-sidebar > row:selected {
    background-color: ${accent} !important;
}
`;

    const gtk3Content = commonTop + gtk3Mid + commonBottom;
    const gtk4Content = commonTop + gtk4Mid + commonBottom;

    const combinedContent = gtk3Content + "===SPLIT===" + gtk4Content;

    const customCommand = `
GTK3_CONTENT="\${1%%===SPLIT===*}"
GTK4_CONTENT="\${1##*===SPLIT===}"

safe_write_import() {
    local file="$1"
    local import_line="$2"
    if [ ! -f "$file" ]; then
        echo "$import_line" > "$file"
    elif ! grep -qF "$import_line" "$file"; then
        sed -i "1i\\$import_line" "$file"
    fi
}

IMPORT_LINE='@import url("yaks.css");'

# GTK4
GTK4_DIR="$HOME/.config/gtk-4.0"
mkdir -p "$GTK4_DIR"
printf '%s' "$GTK4_CONTENT" > "$GTK4_DIR/yaks.css"
safe_write_import "$GTK4_DIR/gtk.css" "$IMPORT_LINE"
safe_write_import "$GTK4_DIR/gtk-dark.css" "$IMPORT_LINE"

# GTK3
GTK3_DIR="$HOME/.config/gtk-3.0"
mkdir -p "$GTK3_DIR"
printf '%s' "$GTK3_CONTENT" > "$GTK3_DIR/yaks.css"
safe_write_import "$GTK3_DIR/gtk.css" "$IMPORT_LINE"

# GSettings
TARGET_GTK_THEME="adw-gtk3-dark"
COLOR_SCHEME="prefer-dark"
if [ "${mode}" = "light" ]; then
    TARGET_GTK_THEME="adw-gtk3"
    COLOR_SCHEME="prefer-light"
fi

THEME_FOUND=false
for dir in /usr/share/themes ~/.local/share/themes /run/current-system/sw/share/themes; do
    if [ -d "$dir" ] && [ -d "$dir/$TARGET_GTK_THEME" ]; then
        THEME_FOUND=true
        break
    fi
done
if [ "$THEME_FOUND" = true ]; then
    dconf write /org/gnome/desktop/interface/gtk-theme "'$TARGET_GTK_THEME'"
fi
dconf write /org/gnome/desktop/interface/color-scheme "'$COLOR_SCHEME'"

# Force reload
if [ "${context}" != "startup" ]; then
    dconf write /org/gnome/desktop/a11y/interface/high-contrast true
    sleep 0.1
    dconf write /org/gnome/desktop/a11y/interface/high-contrast false
fi
`;

    return {
        customCommand: customCommand,
        content: combinedContent
    };
}
