.pragma library

function generate(colors, opacity, mode, context) {
    let content = `-- Generated by Quickshell - DO NOT EDIT\nreturn {\n`;
    for (let key in colors) {
        if (key !== "name" && typeof colors[key] === "string") {
            content += `  ${key} = "${colors[key]}",\n`;
        }
    }
    content += `}\n`;

    return {
        destination: "~/.cache/quickshell/themes/nvim.lua",
        content: content,
        reloadCommand: "pkill -USR1 nvim || true"
    };
}
