.pragma library

function generate(colors, opacity, mode, context) {
    const bg = colors.base00 || "#000000";
    const surface = colors.base01 || bg;
    const surfaceAlt = colors.base03 || surface;
    const text = colors.base05 || "#ffffff";
    const textDim = colors.base04 || "#888888";
    const primary = colors[colors.primaryIdx] || colors.base0D;
    const secondary = colors[colors.secondaryIdx] || colors.base0E;

    let hexPrimary = primary.replace("#", "");
    let textSelection = `#${hexPrimary}4D`;

    const content = `/* 
 * Quickshell Tokens for Obsidian (Minimal Tokens Optimized)
 * Generated by ag-quickshell
 */

.theme-dark, .theme-light, :root {
    /* Core Minimal Variables */
    --bg1: ${surface} !important;
    --bg2: ${bg} !important;
    --bg3: ${surfaceAlt} !important;
    --tx1: ${text} !important;
    --tx2: ${textDim} !important;
    --tx3: ${textDim} !important;
    --ui1: ${surfaceAlt} !important;
    --ui2: ${surfaceAlt} !important;
    --ui3: ${surface} !important;
    --ax1: ${primary} !important;
    --ax2: ${secondary} !important;
    --ax3: ${primary} !important;

    /* Code Blocks */
    --code-background: rgba(0, 0, 0, 0.25) !important;
    --code-normal: var(--tx1) !important;

    /* Obsidian Core Mapping */
    --background-primary: var(--bg1);
    --background-primary-alt: var(--bg2);
    --background-secondary: var(--bg2);
    --background-secondary-alt: var(--bg3);
    --titlebar-background: var(--bg2);
    --titlebar-background-focused: var(--bg2);

    /* Icon Variables */
    --icon-color: var(--tx1) !important;
    --icon-color-hover: var(--tx1) !important;
    --icon-color-active: var(--ax1) !important;
    --icon-color-focused: var(--ax1) !important;
    --icon-muted: var(--tx2) !important;
    
    /* Interactive Elements & Highlights */
    --text-selection: ${textSelection} !important;
    --link-color: var(--ax1) !important;
    --link-color-hover: var(--ax2) !important;
    --link-external-color: var(--ax1) !important;
    --link-external-color-hover: var(--ax2) !important;
    --text-accent-hover: var(--ax2) !important;

    /* Settings / Modal Variables */
    --background-modifier-cover: rgba(0, 0, 0, 0.5);
}

/* Sidebar, Ribbon, and Navigation containers */
.mod-left-split, 
.mod-right-split,
.workspace-ribbon,
.side-dock-settings,
.nav-container,
.workspace-tab-header-container,
.modal,
.side-dock-ribbon {
    background-color: var(--bg2) !important;
}

/* UI element visibility (Text and Icons) */
.nav-folder-title, 
.nav-file-title,
.workspace-tab-header-inner-title,
.view-header-title,
.side-dock-ribbon-action,
.nav-action-button,
.clickable-icon,
.tab-header-title,
.titlebar-text,
.titlebar-button,
.view-header-icon,
.vertical-tab-nav-item,
.setting-item-name,
.setting-item-description {
    color: var(--tx1) !important;
    opacity: 1 !important;
}

/* Active elements */
.workspace-tab-header.is-active,
.side-dock-ribbon-action.is-active,
.vertical-tab-nav-item.is-active {
    background-color: var(--bg1) !important;
    color: var(--tx1) !important;
}

/* Code block differentiation */
.markdown-rendered code,
.markdown-rendered pre {
    background-color: var(--code-background) !important;
    border: 1px solid var(--ui1) !important;
}

/* Tab container border */
.workspace-tab-header-container {
    border-bottom: 1px solid var(--ui1) !important;
}
`;

    const customCommand = `
OBSIDIAN_CONFIG="$HOME/.config/obsidian/obsidian.json"
if [ -f "$OBSIDIAN_CONFIG" ]; then
    VAULTS=$(grep "\\\"path\\\":" "$OBSIDIAN_CONFIG" | sed -E 's/.*:[[:space:]]*"([^"]*)".*/\\1/')
    for vault in $VAULTS; do
        if [ -d "$vault" ]; then
            SNIPPET_DIR="$vault/.obsidian/snippets"
            mkdir -p "$SNIPPET_DIR"
            printf '%s' "$1" > "$SNIPPET_DIR/yaks.css"
            
            APP_JSON="$vault/.obsidian/appearance.json"
            if [ -f "$APP_JSON" ]; then
                if ! grep -q "\\\"yaks\\\"" "$APP_JSON"; then
                    if grep -q "\\\"enabledSnippets\\\":" "$APP_JSON"; then
                        sed -i 's/"enabledSnippets":[[:space:]]*\\[/"enabledSnippets": ["yaks", /' "$APP_JSON"
                    else
                        sed -i 's/}$/, "enabledSnippets": ["yaks"]}/' "$APP_JSON"
                    fi
                fi
            else
                echo '{"enabledSnippets": ["yaks"]}' > "$APP_JSON"
            fi
        fi
    done
fi
`;

    return {
        customCommand: customCommand,
        content: content
    };
}
