.pragma library

function generate(colors, opacity, mode, context) {
    const bg = colors.base00 || "#000000";
    const surface = colors.base01 || bg;
    const surfaceHover = colors.base02 || surface;
    const surfaceAlt = colors.base03 || surfaceHover;
    const textDim = colors.base04 || "#888888";
    const text = colors.base05 || "#ffffff";
    const base08 = colors.base08 || "#F38BA8"; // Red
    const base09 = colors.base09 || "#FAB387"; // Orange
    const base0A = colors.base0A || "#F9E2AF"; // Yellow
    const base0B = colors.base0B || "#A6E3A1"; // Green
    const base0C = colors.base0C || "#94E2D5"; // Cyan
    const base0D = colors.base0D || "#89B4FA"; // Blue
    const base0E = colors.base0E || "#CBA6F7"; // Purple
    const base0F = colors.base0F || "#F2CDCD"; // Pink/Brown
    const primary = colors[colors.primaryIdx] || base0D;
    const secondary = colors[colors.secondaryIdx] || base0E;

    let hexPrimary = primary.replace("#", "");
    let textSelection = `#${hexPrimary}4D`;

    const content = `/* 
 * Generated by Yaks
 */

body {
    /* Core Backgrounds */
    --background-primary: ${surface} !important;
    --background-primary-alt: ${bg} !important;
    --background-secondary: ${bg} !important;
    --background-secondary-alt: ${surfaceAlt} !important;
    --background-modifier-hover: ${surfaceHover} !important;
    --background-modifier-active-hover: ${surfaceHover} !important;
    --background-modifier-border: ${surfaceHover} !important;
    --background-modifier-border-hover: ${surfaceAlt} !important;
    --background-modifier-border-focus: ${primary} !important;
    --background-modifier-error: ${base08} !important;
    --background-modifier-error-hover: ${base08} !important;
    --background-modifier-success: ${base0B} !important;
    
    /* Interactive */
    --interactive-normal: ${surface} !important;
    --interactive-hover: ${surfaceHover} !important;
    --interactive-accent: ${primary} !important;
    --interactive-accent-hover: ${secondary} !important;

    /* Text */
    --text-normal: ${text} !important;
    --text-muted: ${textDim} !important;
    --text-faint: ${textDim} !important;
    --text-on-accent: ${bg} !important;
    --text-error: ${base08} !important;
    --text-success: ${base0B} !important;
    --text-warning: ${base0A} !important;

    /* Accent & Links */
    --text-selection: ${textSelection} !important;
    --text-accent: ${primary} !important;
    --text-accent-hover: ${secondary} !important;
    --link-color: ${primary} !important;
    --link-color-hover: ${secondary} !important;
    --link-external-color: ${primary} !important;
    --link-external-color-hover: ${secondary} !important;

    /* Titlebar & Tabs */
    --titlebar-background: ${bg} !important;
    --titlebar-background-focused: ${bg} !important;
    --tab-background-active: ${surface} !important;
    --tab-text-active: ${text} !important;
    --tab-text-active-focused: ${text} !important;
    --workspace-background-translucent: ${bg} !important;

    /* Code Blocks */
    --code-background: ${surfaceHover} !important;
    --code-normal: ${text} !important;
    --code-comment: ${textDim} !important;
    --code-function: ${base0D} !important;
    --code-important: ${base0E} !important;
    --code-keyword: ${base0E} !important;
    --code-property: ${base0C} !important;
    --code-punctuation: ${textDim} !important;
    --code-string: ${base0B} !important;
    --code-tag: ${base0A} !important;
    --code-value: ${base09} !important;

    /* UI Elements */
    --icon-color: ${text} !important;
    --icon-color-hover: ${text} !important;
    --icon-color-active: ${primary} !important;
    --icon-color-focused: ${primary} !important;
    --icon-muted: ${textDim} !important;

    --nav-item-color: ${text} !important;
    --nav-item-color-hover: ${primary} !important;
    --nav-item-color-active: ${primary} !important;
    --nav-item-background-hover: ${surfaceHover} !important;
    --nav-item-background-active: ${textSelection} !important;
    --nav-item-background-selected: ${textSelection} !important;
    
    --tag-color: ${text} !important;
    --tag-color-hover: ${primary} !important;
    --tag-background: ${surfaceHover} !important;
    --tag-background-hover: ${surfaceAlt} !important;

    --divider-color: ${surfaceHover} !important;
    --divider-color-hover: ${surfaceAlt} !important;

    --scrollbar-active-thumb-bg: ${surfaceAlt} !important;
    --scrollbar-bg: transparent !important;
    --scrollbar-thumb-bg: ${surfaceHover} !important;

    /* Base Palette Overrides */
    --color-red: ${base08} !important;
    --color-orange: ${base09} !important;
    --color-yellow: ${base0A} !important;
    --color-green: ${base0B} !important;
    --color-cyan: ${base0C} !important;
    --color-blue: ${base0D} !important;
    --color-purple: ${base0E} !important;
    --color-pink: ${base0F} !important;

    /* Prompt/Modal */
    --prompt-background: ${bg} !important;
    --prompt-border-color: ${surfaceHover} !important;
    --modal-background: ${bg} !important;
    --modal-border-color: ${surfaceHover} !important;

    /* Graph View */
    --graph-text: ${text} !important;
    --graph-line: ${surfaceHover} !important;
    --graph-node: ${textDim} !important;
    --graph-node-unresolved: ${surfaceHover} !important;
    --graph-node-focused: ${primary} !important;
    --graph-node-tag: ${base0A} !important;
    --graph-node-attachment: ${base0B} !important;

    /* Settings / Modal Variables */
    --background-modifier-cover: rgba(0, 0, 0, 0.5);
    --background-modifier-form-field: ${surfaceHover} !important;
    --background-modifier-form-field-highlighted: ${surfaceAlt} !important;
}

/* Explicit class overrides for the Settings sidebar (vertical tabs) */
.vertical-tab-nav-item {
    color: var(--nav-item-color) !important;
}
.vertical-tab-nav-item svg {
    color: var(--icon-color) !important;
    opacity: 1 !important;
}
.vertical-tab-nav-item:hover {
    background-color: var(--nav-item-background-hover) !important;
    color: var(--nav-item-color-hover) !important;
}
.vertical-tab-nav-item:hover svg {
    color: var(--icon-color-hover) !important;
}
.vertical-tab-nav-item.is-active {
    background-color: var(--nav-item-background-active) !important;
    color: var(--nav-item-color-active) !important;
}
.vertical-tab-nav-item.is-active svg {
    color: var(--icon-color-active) !important;
}

/* Remove structural horizontal borders, shadows, and distinct header backgrounds */
.nav-header,
.workspace-leaf-header,
.workspace-tab-header-container,
.workspace-tab-header-inner {
    background-color: transparent !important;
    border: none !important;
    box-shadow: none !important;
}

.nav-header::after,
.workspace-leaf-header::after,
.workspace-tab-header-container::after,
.workspace-tab-header-inner::after {
    display: none !important;
}

/* Ensure no borders leak from the leaf contents */
.workspace-leaf-content,
.view-content,
.view-header {
    border: none !important;
    box-shadow: none !important;
}

/* Force both sidebars to perfectly match the secondary background color */
.workspace-split.mod-left-split,
.workspace-split.mod-right-split {
    background-color: var(--background-secondary) !important;
    /* Redefine primary backgrounds *inside* the sidebars so all internal panes match */
    --background-primary: var(--background-secondary) !important;
    --background-primary-alt: var(--background-secondary) !important;
}
`;

    const customCommand = `
OBSIDIAN_CONFIG="$HOME/.config/obsidian/obsidian.json"
if [ -f "$OBSIDIAN_CONFIG" ]; then
    VAULTS=$(grep -o '"path":"[^"]*"' "$OBSIDIAN_CONFIG" | cut -d'"' -f4)
    for vault in $VAULTS; do
        if [ -d "$vault" ]; then
            SNIPPET_DIR="$vault/.obsidian/snippets"
            mkdir -p "$SNIPPET_DIR"
            printf '%s' "$1" > "$SNIPPET_DIR/yaks.css"
            
            APP_JSON="$vault/.obsidian/appearance.json"
            if [ -f "$APP_JSON" ]; then
                if ! grep -q "\\\"yaks\\\"" "$APP_JSON"; then
                    if grep -q "\\\"enabledSnippets\\\":" "$APP_JSON"; then
                        sed -i 's/"enabledSnippets":[[:space:]]*\\[/"enabledSnippets": ["yaks", /' "$APP_JSON"
                    else
                        sed -i 's/}$/, "enabledSnippets": ["yaks"]}/' "$APP_JSON"
                    fi
                fi
            else
                echo '{"enabledSnippets": ["yaks"]}' > "$APP_JSON"
            fi
        fi
    done
fi
`;

    return {
        customCommand: customCommand,
        content: content
    };
}
